Added end to end segmented timing for the scan loop. May have found an issue.

diff --git a/scripts/run_scan b/scripts/run_scan
--- a/scripts/run_scan
+++ b/scripts/run_scan
@@ -36,11 +36,11 @@ if [ $? -eq 1 ]; then
 fi
 
 # Make sure there is at least one processe named vegasFitsWriter being run by the current user
-# pgrep -u $USER vegasFitsWriter > /dev/null
-# if [ $? -eq 1 ]; then
-#     echo ">   ERROR: vegasFitsWriter is not running for the current user"
-#     do_exit=1
-# fi
+pgrep -u $USER vegasFitsWriter > /dev/null
+if [ $? -eq 1 ]; then
+    echo ">   ERROR: vegasFitsWriter is not running for the current user"
+    do_exit=1
+fi
 
 if [ "$do_exit" -eq 1 ]; then
     echo "> Exiting..."
@@ -59,5 +59,5 @@ echo "> Starting the scan"
 echo ">   Sending the command \"$cmd\" to fake_gpu"
 echo "$cmd" >> /tmp/tchamber/fake_gpu_control
 
-# echo ">   Sending the command \"$cmd\" to vegasFitsWriter"
-# echo "$cmd" >> /tmp/tchamber/vegas_fits_control
+echo ">   Sending the command \"$cmd\" to vegasFitsWriter"
+echo "$cmd" >> /tmp/tchamber/vegas_fits_control
